<script type="text/javascript">
    function mostrar4(id) {
        if (id == "I") {
            $("#I").show();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "II") {
            $("#I").hide();
            $("#II").show();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "III") {
            $("#I").hide();
            $("#II").hide();
            $("#III").show();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "IV") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").show();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "V") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").show();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "VI") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").show();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "VII") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").show();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "VIII") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").show();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "IX") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").show();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "X") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").show();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "XI") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").show();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "XII") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").show();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "XIII") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").show();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "XIV") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").show();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "XV") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").show();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "XVI") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").show();
            $("#XVII").hide();
            $("#XVIII").hide();
        }

        if (id == "XVII") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").show();
            $("#XVIII").hide();
        }

        if (id == "XVIII") {
            $("#I").hide();
            $("#II").hide();
            $("#III").hide();
            $("#IV").hide();
            $("#V").hide();
            $("#VI").hide();
            $("#VII").hide();
            $("#VIII").hide();
            $("#IX").hide();
            $("#X").hide();
            $("#XI").hide();
            $("#XII").hide();
            $("#XIII").hide();
            $("#XIV").hide();
            $("#XV").hide();
            $("#XVI").hide();
            $("#XVII").hide();
            $("#XVIII").show();
        }
    }
</script>
